### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana-javascript-agent#39]
Add sampling control. A probabilistic sampling (eg, X% of events) would be a good start. Consider if to apply per-event, or per-session.

**Comment by cedricziel** [comment]
This should be configurable and default should be to sample everything to enable getting the most accurate view on matters.

**Comment by rexwangcc** [comment]
Sorry for the bump, any updates on the sampling feature?

**Comment by codecapitano** [comment]
Session Based sampling

See: Design Doc: [Session Based Sampling](https://docs.google.com/document/d/1izVFMjDk4pZl559E3qqAWGdcKCyWMoQaRre3ywbVOXs/edit#heading=h.5sybau7waq2q)



```[tasklist]
### Tasks
- [ ] Implement sampling based on factor (%)
- [ ] Implement sampling based on characteristics (result is calculated with custom function) 
```

**Comment by codecapitano** [comment]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by codecapitano** [comment]
Relates to #129

**Comment by codecapitano** [comment]
Sampling is released and to use ready (v1.3.1)
